# Generated by Django 4.1.5 on 2023-04-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_cartitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="care",
            field=models.TextField(default=1),
        ),
    ]
